name: Create Arduino zip library

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Move readme
        run: mv README.md ./src/

      - name: Rename folder
        run: mv src LedStripController

      - name: Zip source code
        run: zip -r -q LedStripController.zip LedStripController
      
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            LedStripController.zip
